import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    TIMEFRAME = "4h"
    TIMEFRAME_MINUTES = 240
    LEVERAGE = 10
    INITIAL_CAPITAL = 10000.0
    MARGIN_MAX_RATIO = 0.85
    KELLY_FRACTIONAL = 0.50
    MAX_CONCURRENT_POSITIONS = 4
    KELLY_WINDOW = 50
    SL_ATR_MULT = 1.5
    TP_ATR_MULT = 6.0
    TRAIL_ACTIVATION_MULT = 0.3
    TRAIL_DISTANCE_MULT = 1.5
    MIN_VOLUME_USDT = 10_000_000
    MIN_AVG_VOLUME_USDT = 1_000_000
    MAX_ATR_PCT = 10.0
    MIN_MOMENTUM_STRENGTH = 1.5
    SCORE_ENTRY_THRESHOLD = 4
    RSI_LEN = 14
    MACD_FAST = 12
    MACD_SLOW = 26
    MACD_SIGNAL = 9
    EMA_FAST = 50
    EMA_SLOW = 200
    VOL_SMA_LEN = 20
    VOL_MULTIPLIER = 1.2
    ATR_LEN = 14
    MOMENTUM_LOOKBACK = 24
    MOMENTUM_TOP_N = 3
    MOMENTUM_SCAN_COINS = 20
    TOP_N_COINS = 20
    TOP_N_UPDATE_INTERVAL = 3600
    UPDATE_EXCHANGE_STOP = True

    MG_BASE_MULT = 1.0
    MG_MULTIPLIER = 1.5
    MG_MAX_LEVEL = 3

    MIN_POSITION_MARGIN = 2000
    MAX_MARGIN_PCT_PER_POSITION = 0.50
    RISK_PER_TRADE_PCT = 0.30

    BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
    BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", "")
    BINANCE_TESTNET = os.getenv("BINANCE_TESTNET", "true").lower() == "true"

    BACKTEST_START = "2026-01-20"
    BACKTEST_END = "2026-07-20"

    LOG_DIR = "storage/logs"
    HISTORY_DIR = "data/history"
